"""
arc-agent-pay
=============
A Python SDK that makes it trivial for any AI agent to discover,
pay for, and consume API services using USDC nanopayments on Arc.

Quick start
-----------
    import os
    from arc_agent_pay import PaymentClient, ServiceRegistry
    from arc_agent_pay.models import Chain
    from eth_account import Account

    registry = ServiceRegistry()
    services = registry.search("crypto prices")

    account = Account.from_key("0x" + os.environ["AGENT_PRIVATE_KEY"])

    async with PaymentClient(account=account, budget_usdc="0.05") as client:
        response = await client.get(services[0].url)
        print(response.json())
        print(client.summary())
"""

from .budget import BudgetGuard
from .interceptor import PaymentClient, PaymentExchange, PaymentExchangeObserver
from .models import AssuranceTerms, Chain, Wallet, Service, Payment, Budget, PaymentRequest
from .assurance import (
    AdjudicationBody,
    AdjudicationPayload,
    AdjudicationSLA,
    AdjudicationTiming,
    AssuranceEvidence,
    AssuranceSettlementBinding,
    AssuranceSettlementRelay,
    AssuranceSettlementResult,
    AssuranceStore,
    AssuranceStoreError,
    AssuranceVerdict,
    ArcPaymentVerifier,
    BondTransactionResult,
    Dispute,
    DisputeStatus,
    GenLayerAdjudicationClient,
    GenLayerDeploymentArtifact,
    GenLayerFeeEstimate,
    GenLayerStoredVerdict,
    GenLayerSubmission,
    GenLayerTransactionStatus,
    FinalizedGenLayerDeployment,
    FinalizedGenLayerAdjudication,
    STUDIO_DEV_CHAIN_ID,
    STUDIO_DEV_NETWORK,
    STUDIO_DEV_RPC_URL,
    SettlementRecord,
    SettlementStatus,
    VerifiedArcPayment,
    WarrantyBondClient,
    adjudication_input_hash,
    contract_source_hash,
    contract_source_metadata,
    dispute_id,
    payment_id_hash,
    load_deployment_artifact,
)
from .payment_store import (
    InMemoryPaymentStore,
    PaymentStore,
    SqlitePaymentStore,
    default_payment_store_path,
)
from .policy import PaymentPolicy
from .registry import Discovery, SemanticServiceRegistry, ServiceRegistry
from .spending import InMemorySpendLedger, SpendCaps, SqliteSpendLedger
from .workflow import (
    DeliveryEvidence,
    EscrowClient,
    EscrowStatus,
    Erc8183Client,
    Erc8183CreateResult,
    Erc8183Job,
    Erc8183JobSpec,
    Erc8183Status,
    SignedFundingAuthorization,
    SignedValidationVerdict,
    ValidationVerdict,
    Verifier,
    WorkOrder,
    hash_content,
    deliverable_commitment,
    sign_funding_authorization,
    sign_verdict,
    verify_signed_verdict,
    verdict_commitment,
)
from .exceptions import (
    ArcAgentPayError,
    InsufficientFundsError,
    PaymentFailedError,
    PaymentTimeoutError,
    InvalidPaymentRequestError,
    ArcPaymentVerificationError,
    WrongArcChain,
    MissingTransactionReference,
    InvalidTransactionReference,
    TransactionNotFound,
    TransactionReverted,
    InsufficientConfirmations,
    WrongPaymentNetwork,
    WrongPaymentAsset,
    ProviderBindingMismatch,
    PaymentTransferNotFound,
    AmbiguousPaymentTransfer,
    PaymentAmountMismatch,
    AdjudicationPayloadTooLarge,
    GenLayerAdjudicationError,
    GenLayerExecutionFailed,
    GenLayerFinalityTimeout,
    GenLayerDeploymentError,
    GenLayerNetworkMismatch,
    GenLayerFeeEstimationFailed,
    GenLayerInsufficientBalance,
    GenLayerDeploymentArtifactError,
    GenLayerSubmissionOutcomeUnknown,
    GenLayerTransportRetryExhausted,
    AssuranceSettlementError,
    SettlementBindingError,
    SettlementIneligible,
    SettlementPreflightError,
    SettlementAlreadyProcessed,
    SettlementSubmissionOutcomeUnknown,
    SettlementPending,
    SettlementTransactionFailed,
    GenLayerTransactionNotFinal,
    GenLayerVerdictBindingMismatch,
    GenLayerVerdictNotFound,
    PaymentPolicyError,
    PaymentStoreError,
    ServiceNotFoundError,
    ServiceRegistrationError,
    WorkflowError,
    InvalidFundingAuthorizationError,
    InvalidVerdictError,
)

__version__ = "0.4.0"

__all__ = [
    # Core classes
    "PaymentClient",
    "PaymentExchange",
    "PaymentExchangeObserver",
    "ServiceRegistry",
    "SemanticServiceRegistry",
    "Discovery",
    "BudgetGuard",
    "PaymentPolicy",
    "PaymentStore",
    "InMemoryPaymentStore",
    "SqlitePaymentStore",
    "default_payment_store_path",
    # Spending caps
    "SpendCaps",
    "InMemorySpendLedger",
    "SqliteSpendLedger",
    # Validation-gated workflows
    "WorkOrder",
    "DeliveryEvidence",
    "EscrowClient",
    "EscrowStatus",
    "Erc8183Client",
    "Erc8183CreateResult",
    "Erc8183Job",
    "Erc8183JobSpec",
    "Erc8183Status",
    "SignedFundingAuthorization",
    "ValidationVerdict",
    "SignedValidationVerdict",
    "Verifier",
    "hash_content",
    "deliverable_commitment",
    "sign_funding_authorization",
    "sign_verdict",
    "verify_signed_verdict",
    "verdict_commitment",
    # Models
    "Chain",
    "Wallet",
    "Service",
    "Payment",
    "Budget",
    "PaymentRequest",
    "AdjudicationBody",
    "AdjudicationPayload",
    "AdjudicationSLA",
    "AdjudicationTiming",
    "AssuranceTerms",
    "AssuranceEvidence",
    "AssuranceSettlementBinding",
    "AssuranceSettlementRelay",
    "AssuranceSettlementResult",
    "AssuranceStore",
    "AssuranceStoreError",
    "AssuranceVerdict",
    "ArcPaymentVerifier",
    "BondTransactionResult",
    "Dispute",
    "DisputeStatus",
    "GenLayerAdjudicationClient",
    "GenLayerDeploymentArtifact",
    "GenLayerFeeEstimate",
    "GenLayerStoredVerdict",
    "GenLayerSubmission",
    "GenLayerTransactionStatus",
    "FinalizedGenLayerDeployment",
    "FinalizedGenLayerAdjudication",
    "STUDIO_DEV_CHAIN_ID",
    "STUDIO_DEV_NETWORK",
    "STUDIO_DEV_RPC_URL",
    "SettlementRecord",
    "SettlementStatus",
    "VerifiedArcPayment",
    "WarrantyBondClient",
    "adjudication_input_hash",
    "contract_source_hash",
    "contract_source_metadata",
    "dispute_id",
    "payment_id_hash",
    "load_deployment_artifact",
    # Exceptions
    "ArcAgentPayError",
    "InsufficientFundsError",
    "PaymentFailedError",
    "PaymentTimeoutError",
    "InvalidPaymentRequestError",
    "ArcPaymentVerificationError",
    "WrongArcChain",
    "MissingTransactionReference",
    "InvalidTransactionReference",
    "TransactionNotFound",
    "TransactionReverted",
    "InsufficientConfirmations",
    "WrongPaymentNetwork",
    "WrongPaymentAsset",
    "ProviderBindingMismatch",
    "PaymentTransferNotFound",
    "AmbiguousPaymentTransfer",
    "PaymentAmountMismatch",
    "AdjudicationPayloadTooLarge",
    "GenLayerAdjudicationError",
    "GenLayerExecutionFailed",
    "GenLayerFinalityTimeout",
    "GenLayerDeploymentError",
    "GenLayerNetworkMismatch",
    "GenLayerFeeEstimationFailed",
    "GenLayerInsufficientBalance",
    "GenLayerDeploymentArtifactError",
    "GenLayerSubmissionOutcomeUnknown",
    "GenLayerTransportRetryExhausted",
    "AssuranceSettlementError",
    "SettlementBindingError",
    "SettlementIneligible",
    "SettlementPreflightError",
    "SettlementAlreadyProcessed",
    "SettlementSubmissionOutcomeUnknown",
    "SettlementPending",
    "SettlementTransactionFailed",
    "GenLayerTransactionNotFinal",
    "GenLayerVerdictBindingMismatch",
    "GenLayerVerdictNotFound",
    "PaymentPolicyError",
    "PaymentStoreError",
    "ServiceNotFoundError",
    "ServiceRegistrationError",
    "WorkflowError",
    "InvalidFundingAuthorizationError",
    "InvalidVerdictError",
]
