"""
llm/template.py — keyless fallback report formatter.

When no LLM provider is configured, the agent still produces a useful,
structured report by formatting the fetched API data directly. This keeps the
SDK runnable with zero API keys.
"""

from __future__ import annotations

from typing import Any


def template_report(topic: str, fetched_data: dict[str, Any]) -> str:
    """Build a Markdown report from fetched data without calling any LLM."""
    sections: list[str] = [
        f"# Research Report: {topic}",
        "*Generated by arc-agent-pay (template mode)*\n",
    ]

    for _name, data in fetched_data.items():
        if "brief" in data:
            sections += [data["brief"], ""]

    for _name, data in fetched_data.items():
        if "data" in data and isinstance(data["data"], dict):
            sections.append("## Market Prices")
            for symbol, info in data["data"].items():
                change = info.get("change_24h_pct", 0)
                direction = "▲" if change >= 0 else "▼"
                sections.append(
                    f"- **{symbol}**: ${info.get('price_usd', 'N/A'):,} "
                    f"{direction} {abs(change):.2f}%"
                )
            sections.append("")

    for _name, data in fetched_data.items():
        if "headlines" in data:
            cat = data.get("category", "General")
            sections.append(f"## Latest News ({cat.title()})")
            for h in data["headlines"][:5]:
                sections.append(f"- {h['title']} *(via {h['source']})*")
            sections.append("")

    for _name, data in fetched_data.items():
        if "transactions" in data:
            total = data.get("total_volume_usd", 0)
            unusual = data.get("unusual_count", 0)
            sections.append("## On-Chain Whale Activity (24h)")
            sections.append(f"- **Total Volume**: ${total:,.0f}")
            sections.append(f"- **Unusual Activity**: {unusual} transactions flagged")
            top_tx = data["transactions"][0] if data["transactions"] else {}
            if top_tx:
                sections.append(
                    f"- **Largest Move**: ${top_tx.get('amount_usd', 0):,.0f} "
                    f"({top_tx.get('direction', '').upper()})"
                )
            sections.append("")

    return "\n".join(sections)
